/* generated by
   tools::package_native_routine_registration_skeleton("C:/Users/Sophie/MesDossiers/TravailPR/Thierry/Dehghan/package/gte") */

#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* FIXME: 
 Check these declarations against the C/Fortran source code.
 */

/* .C calls */
extern void GetAlpha(void *, void *, void *, void *, void *, void *);
extern void St2(void *, void *, void *, void *, void *, void *, void *, void *);

static const R_CMethodDef CEntries[] = {
  {"GetAlpha", (DL_FUNC) &GetAlpha, 6},
  {"St2",      (DL_FUNC) &St2,      8},
  {NULL, NULL, 0}
};

void R_init_gte(DllInfo *dll)
{
  R_registerRoutines(dll, CEntries, NULL, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
